@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}


interface User {

    val id: String
    val name: String
    val email: String
    val surname: String
    val address: UserAddress
    val phoneNum: String
    val username: String
    val password: String

    fun getRole(): UserRole
}


@enduml