name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Κάνε checkout του κώδικα
      - uses: actions/checkout@v3

      # 2) Βάλε Java (π.χ. 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Εγκατάστησε Android SDK & αποδέξου licenses
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 36
          ndk: false

      # 4) Τρέξε το Gradle build + tests
      - name: Build & Test with Gradle
        run: ./gradlew clean assembleDebug test --no-daemon

